In [64]:
## Import libraries
import pandas as pd

In [65]:
## Read CSV file
url = 'https://raw.githubusercontent.com/mhenson1989/group_one_project/main/clean_data.csv'
clean_data = pd.read_csv(url, index_col = False)
clean_data

,Date,77449,77494,79936,77084,78660,77479,77429,75217,77584,...,75246,78742,77417,78152,77534,77873,77444,77046,77464,77476
0,2000-01-31,107002.0,223338.0,90849.0,106614.0,162156.0,237597.0,162149.0,70761.0,173387.0,...,132633.0,115005.0,110935.0,130477.0,91467.0,138760.0,113315.0,208217.0,190359.0,219063.0
1,2000-02-29,107015.0,223655.0,90849.0,106559.0,162614.0,238554.0,162038.0,70924.0,173869.0,...,133152.0,115269.0,110810.0,131608.0,91741.0,140062.0,113063.0,207768.0,192138.0,220646.0
2,2000-03-31,106817.0,224374.0,90882.0,106301.0,162810.0,239507.0,161740.0,70913.0,174256.0,...,134439.0,114676.0,110604.0,132040.0,91658.0,140856.0,112895.0,205635.0,195121.0,218306.0
3,2000-04-30,106822.0,225594.0,90848.0,106249.0,163328.0,241449.0,161732.0,71083.0,175158.0,...,134984.0,113913.0,110701.0,132628.0,91854.0,141111.0,113150.0,202675.0,200202.0,216508.0
4,2000-05-31,106853.0,225159.0,90868.0,106214.0,163675.0,242161.0,161787.0,71157.0,176019.0,...,134142.0,112561.0,110444.0,132123.0,92225.0,140032.0,112565.0,200162.0,203636.0,212277.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
267,2022-04-30,273285.0,480021.0,184519.0,268096.0,502647.0,509862.0,363840.0,217146.0,362259.0,...,372382.0,432786.0,254787.0,376435.0,257012.0,395242.0,275938.0,341963.0,315907.0,410628.0
268,2022-05-31,279389.0,491404.0,188144.0,273603.0,509584.0,520541.0,371762.0,222399.0,368709.0,...,378179.0,439025.0,259659.0,379968.0,261677.0,397600.0,279804.0,346886.0,323898.0,416218.0
269,2022-06-30,284432.0,498890.0,191609.0,277991.0,505334.0,526923.0,378324.0,227489.0,373389.0,...,382940.0,435275.0,262033.0,378320.0,264029.0,403756.0,286658.0,349098.0,321533.0,417235.0
270,2022-07-31,287836.0,501155.0,193857.0,280897.0,495371.0,528295.0,382860.0,230092.0,376621.0,...,384114.0,427681.0,261369.0,379071.0,265880.0,410528.0,291269.0,351382.0,317844.0,416401.0
271,2022-08-31,289756.0,499291.0,195569.0,282555.0,482984.0,525565.0,385175.0,230391.0,378372.0,...,384945.0,419775.0,256775.0,379393.0,267189.0,417516.0,290765.0,351022.0,310646.0,413839.0

In [66]:
clean_data = clean_data.set_index('Date')

In [67]:
# Transpose and set index label to Zip_Code
data_tableau = clean_data.transpose().rename_axis('Zip_Code', axis=1)
data_tableau

Zip_Code,2000-01-31,2000-02-29,2000-03-31,2000-04-30,2000-05-31,2000-06-30,2000-07-31,2000-08-31,2000-09-30,2000-10-31,...,2021-11-30,2021-12-31,2022-01-31,2022-02-28,2022-03-31,2022-04-30,2022-05-31,2022-06-30,2022-07-31,2022-08-31
77449,107002.0,107015.0,106817.0,106822.0,106853.0,107066.0,107220.0,107449.0,107831.0,108066.0,...,248777.0,252709.0,256653.0,261312.0,266997.0,273285.0,279389.0,284432.0,287836.0,289756.0
77494,223338.0,223655.0,224374.0,225594.0,225159.0,224825.0,223712.0,224052.0,223656.0,224325.0,...,433465.0,439171.0,445234.0,454715.0,466332.0,480021.0,491404.0,498890.0,501155.0,499291.0
79936,90849.0,90849.0,90882.0,90848.0,90868.0,90827.0,90813.0,90765.0,90232.0,89596.0,...,173345.0,174972.0,176993.0,178975.0,181139.0,184519.0,188144.0,191609.0,193857.0,195569.0
77084,106614.0,106559.0,106301.0,106249.0,106214.0,106382.0,106422.0,106608.0,107009.0,107337.0,...,245999.0,249483.0,252913.0,257067.0,262316.0,268096.0,273603.0,277991.0,280897.0,282555.0
78660,162156.0,162614.0,162810.0,163328.0,163675.0,164035.0,163925.0,164104.0,164240.0,164920.0,...,447053.0,458803.0,469077.0,481480.0,492874.0,502647.0,509584.0,505334.0,495371.0,482984.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77873,138760.0,140062.0,140856.0,141111.0,140032.0,137491.0,135358.0,133486.0,131901.0,130759.0,...,358067.0,368112.0,375304.0,385624.0,390054.0,395242.0,397600.0,403756.0,410528.0,417516.0
77444,113315.0,113063.0,112895.0,113150.0,112565.0,112416.0,111332.0,110828.0,109554.0,109407.0,...,245860.0,250923.0,257861.0,264748.0,270633.0,275938.0,279804.0,286658.0,291269.0,290765.0
77046,208217.0,207768.0,205635.0,202675.0,200162.0,194524.0,193560.0,192489.0,195371.0,192894.0,...,332338.0,333990.0,337446.0,338476.0,340595.0,341963.0,346886.0,349098.0,351382.0,351022.0
77464,190359.0,192138.0,195121.0,200202.0,203636.0,204359.0,205382.0,205847.0,207405.0,208354.0,...,268291.0,272121.0,277811.0,289314.0,303471.0,315907.0,323898.0,321533.0,317844.0,310646.0
77476,219063.0,220646.0,218306.0,216508.0,212277.0,212297.0,214488.0,217336.0,220252.0,220856.0,...,371557.0,374531.0,378538.0,388844.0,400544.0,410628.0,416218.0,417235.0,416401.0,413839.0

In [ ]:
data_tableau.to_csv('tableau_clean.csv', index=True, header=True)